[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sequelize", "mysql2", "ejs"]
  included_files = ["src/views/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
